/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlotDetailsRouteImport } from './routes/slotDetails'
import { Route as LeaderScheduleRouteImport } from './routes/leaderSchedule'
import { Route as GossipRouteImport } from './routes/gossip'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SlotDetailsRoute = SlotDetailsRouteImport.update({
  id: '/slotDetails',
  path: '/slotDetails',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderScheduleRoute = LeaderScheduleRouteImport.update({
  id: '/leaderSchedule',
  path: '/leaderSchedule',
  getParentRoute: () => rootRouteImport,
} as any)
const GossipRoute = GossipRouteImport.update({
  id: '/gossip',
  path: '/gossip',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gossip': typeof GossipRoute
  '/leaderSchedule': typeof LeaderScheduleRoute
  '/slotDetails': typeof SlotDetailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gossip': typeof GossipRoute
  '/leaderSchedule': typeof LeaderScheduleRoute
  '/slotDetails': typeof SlotDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gossip': typeof GossipRoute
  '/leaderSchedule': typeof LeaderScheduleRoute
  '/slotDetails': typeof SlotDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/gossip' | '/leaderSchedule' | '/slotDetails'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/gossip' | '/leaderSchedule' | '/slotDetails'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/gossip'
    | '/leaderSchedule'
    | '/slotDetails'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GossipRoute: typeof GossipRoute
  LeaderScheduleRoute: typeof LeaderScheduleRoute
  SlotDetailsRoute: typeof SlotDetailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/slotDetails': {
      id: '/slotDetails'
      path: '/slotDetails'
      fullPath: '/slotDetails'
      preLoaderRoute: typeof SlotDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderSchedule': {
      id: '/leaderSchedule'
      path: '/leaderSchedule'
      fullPath: '/leaderSchedule'
      preLoaderRoute: typeof LeaderScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gossip': {
      id: '/gossip'
      path: '/gossip'
      fullPath: '/gossip'
      preLoaderRoute: typeof GossipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GossipRoute: GossipRoute,
  LeaderScheduleRoute: LeaderScheduleRoute,
  SlotDetailsRoute: SlotDetailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
